---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: orders
      containers:
        - name: orders
          image: ghcr.io/goodfood-cesi/api-orders:latest
          ports:
            - containerPort: 80
          env:
            - name: DB_DRIVER
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: DB_DRIVER
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: DB_PORT
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: DB_DATABASE
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: DB_PASSWORD
            - name: RESTAURANTS_API_URL
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: RESTAURANTS_API_URL
            - name: PAYPAL_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: PAYPAL_CLIENT_ID
            - name: PAYPAL_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: PAYPAL_CLIENT_SECRET
      imagePullSecrets:
        - name: ghcr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: orders-svc
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: orders
